# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-23 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 23, 19, 5, 7, 272974, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 1, 23, 19, 5, 34, 568580, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
